// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fitness_Diet_Reviewer.Models;

public partial class DailyMealRow
{
    public int DailyMealRowId { get; set; }

    public int? ProductId { get; set; }

    public decimal AmountInGrams { get; set; }

    public int? FitnessDietId { get; set; }

    public string DayOfWeek { get; set; }

    public TimeOnly EatTime { get; set; }

    public virtual FitnessDiet FitnessDiet { get; set; }

    public virtual Food Product { get; set; }
}