// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Fitness_Diet_Reviewer.Models;

public partial class Food
{
    public int FoodId { get; set; }

    public string FoodName { get; set; }

    public decimal Proteins { get; set; }

    public decimal Carbohydrates { get; set; }

    public decimal Fats { get; set; }

    public virtual ICollection<DailyMealRow> DailyMealRows { get; set; } = new List<DailyMealRow>();
}