// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Fitness_Diet_Reviewer.Models;

public partial class Guideline
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int GuidelineId { get; set; }
    public string Content { get; set; }
    public string FitnessInstructorId { get; set; }
    public int FitnessDietId { get; set; }
    public virtual FitnessDiet FitnessDiet { get; set; }
    public virtual ApplicationUser FitnessInstructor { get; set; }
}